/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddGpxDialog: typeof import('./src/components/AddGpxDialog.vue')['default']
    CameraConfiguration: typeof import('./src/components/CameraConfiguration.vue')['default']
    CurseurCenter: typeof import('./src/components/CurseurCenter.vue')['default']
    DelGpxDialog: typeof import('./src/components/DelGpxDialog.vue')['default']
    Deplacement: typeof import('./src/components/Deplacement.vue')['default']
    EvtInfo: typeof import('./src/components/EvtInfo.vue')['default']
    EvtPause: typeof import('./src/components/EvtPause.vue')['default']
    EvtPositionWidget: typeof import('./src/components/EvtPositionWidget.vue')['default']
    EvtsConfiguration: typeof import('./src/components/EvtsConfiguration.vue')['default']
    EvtsWidget: typeof import('./src/components/EvtsWidget.vue')['default']
    EvtVignetteSelection: typeof import('./src/components/EvtVignetteSelection.vue')['default']
    EvtZoom: typeof import('./src/components/EvtZoom.vue')['default']
    Fitre: typeof import('./src/components/Fitre.vue')['default']
    IhmConfiguration: typeof import('./src/components/IhmConfiguration.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    MapCmdWidget: typeof import('./src/components/MapCmdWidget.vue')['default']
    MapDataWidget: typeof import('./src/components/MapDataWidget.vue')['default']
    MapHomeWidget: typeof import('./src/components/MapHomeWidget.vue')['default']
    MenuToolbar: typeof import('./src/components/MenuToolbar.vue')['default']
    MsgAlert: typeof import('./src/components/MsgAlert.vue')['default']
    ParcoursCard: typeof import('./src/components/ParcoursCard.vue')['default']
    PovConfiguration: typeof import('./src/components/PovConfiguration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
  }
}
