/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddGpxDialog: typeof import('./src/components/AddGpxDialog.vue')['default']
    CameraCmdWidget: typeof import('./src/components/CameraCmdWidget.vue')['default']
    DelGpxDialog: typeof import('./src/components/DelGpxDialog.vue')['default']
    EvtPositionWidget: typeof import('./src/components/EvtPositionWidget.vue')['default']
    Fitre: typeof import('./src/components/Fitre.vue')['default']
    MapCmdWidget: typeof import('./src/components/MapCmdWidget.vue')['default']
    MapDataWidget: typeof import('./src/components/MapDataWidget.vue')['default']
    MapHomeWidget: typeof import('./src/components/MapHomeWidget.vue')['default']
    MenuToolbar: typeof import('./src/components/MenuToolbar.vue')['default']
    MsgAlert: typeof import('./src/components/MsgAlert.vue')['default']
    ParcoursCard: typeof import('./src/components/ParcoursCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
    TraceCmdwidget: typeof import('./src/components/TraceCmdwidget.vue')['default']
  }
}
